version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx: 
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '8888:80'
    depends_on: 
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # now we must tell docker compose to look in server folder
    volumes:
      - /app/node_modules
      - ./server:/app # routing container app folder to observe our local server dir 
    environment: 
      - REDIS_HOST=redis # refers to redis service we defined in this file
      - REDIS_PORT=6379
      # default values from postgres docs
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
    depends_on:
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379